---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: instavote
  namespace: flux-system
spec:
  interval: 30s
  path: manifests/monitoring
  prune: true
  timeout: 30s
  healthChecks:
    - kind: Deployment
      name: prometheus
      namespace: flux-system
    - kind: Deployment
      name: grafana
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: monitoring

