---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: flux-system
spec:
  chart:
    spec:
      chart: postgres
      sourceRef:
        kind: HelmRepository
        name: lfs269
  interval: 1m0s
  releaseName: postgres
  targetNamespace: instavote
  values: {}

